version: "3.8"
services:
  crawl-web:
    build: .
    image: kelvie/dcss-webtiles:latest
    ports:
      - 9090:8080
    volumes:
      - crawl-web-data:/data
    restart: unless-stopped

volumes:
  crawl-web-data:
